<a href="https://colab.research.google.com/github/MithunCm29/MachineLearning/blob/main/iris_decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris 
data=load_iris()
x=data.data
y=data.target
names = data.target_names
feature_names = data.feature_names
print(names)
print(feature_names)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(x, y, random_state=50, test_size=0.20)
display(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)
print(X_train)
print(Y_train)

(120, 4)

(30, 4)

(120,)

(30,)

[[7.2 3.2 6.  1.8]
 [5.1 2.5 3.  1.1]
 [6.1 2.8 4.7 1.2]
 [6.7 3.3 5.7 2.5]
 [5.1 3.7 1.5 0.4]
 [4.6 3.1 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [6.  2.2 5.  1.5]
 [5.4 3.  4.5 1.5]
 [5.  3.4 1.5 0.2]
 [4.5 2.3 1.3 0.3]
 [4.9 2.4 3.3 1. ]
 [6.5 3.  5.8 2.2]
 [4.4 2.9 1.4 0.2]
 [7.1 3.  5.9 2.1]
 [5.1 3.5 1.4 0.3]
 [4.4 3.2 1.3 0.2]
 [5.7 3.8 1.7 0.3]
 [6.3 2.5 5.  1.9]
 [5.8 2.8 5.1 2.4]
 [6.6 3.  4.4 1.4]
 [5.4 3.9 1.7 0.4]
 [5.7 4.4 1.5 0.4]
 [6.1 2.9 4.7 1.4]
 [5.8 2.7 5.1 1.9]
 [5.7 2.8 4.1 1.3]
 [7.  3.2 4.7 1.4]
 [5.2 3.5 1.5 0.2]
 [4.4 3.  1.3 0.2]
 [7.7 2.8 6.7 2. ]
 [7.7 3.8 6.7 2.2]
 [6.4 2.9 4.3 1.3]
 [6.3 2.9 5.6 1.8]
 [5.  3.5 1.3 0.3]
 [4.9 3.6 1.4 0.1]
 [6.5 3.  5.5 1.8]
 [6.  2.9 4.5 1.5]
 [5.  3.6 1.4 0.2]
 [5.5 2.3 4.  1.3]
 [5.1 3.8 1.9 0.4]
 [7.3 2.9 6.3 1.8]
 [6.4 3.1 5.5 1.8]
 [6.7 3.1 4.4 1.4]
 [6.4 2.8 5.6 2.1]
 [5.6 2.5 3.9 1.1]
 [4.6 3.2 1.4 0.2]
 [6.3 2.3 4.4 1.3]
 [5.2 4.1 1.5 0.1]
 [5.5 2.5 4.  1.3]
 [6.9 3.1 4.9 1.5]
 [4.7 3.2 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [5.9 3.  4.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf= DecisionTreeClassifier()
model=clf.fit(X_train, Y_train)
from sklearn.metrics import accuracy_score
print("The Accuracy in train set: ",accuracy_score(y_true=Y_train, y_pred=clf.predict(X_train)))
print("The Accuracy in test set: ",accuracy_score(y_true=Y_test, y_pred=clf.predict(X_test)))

The Accuracy in train set:  1.0
The Accuracy in test set:  0.9666666666666667


In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
model1= gnb.fit(X_train, Y_train)
print("The Accuracy in train set: ",accuracy_score(y_true=Y_train, y_pred=gnb.predict(X_train)))
print("The Accuracy in test set: ",accuracy_score(y_true=Y_test, y_pred=gnb.predict(X_test)))

The Accuracy in train set:  0.95
The Accuracy in test set:  0.9333333333333333


In [ ]:
#Preprocessed data for MLP
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
enc = OneHotEncoder()
Y = enc.fit_transform(y[:, np.newaxis]).toarray()

# Scale data to have mean 0 and variance 1 
# which is importance for convergence of the neural network
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

# Split the data set into training and testing
X_train, X_test, Y_train, Y_test = train_test_split(
    X_scaled, Y, test_size=0.2, random_state=2)

n_features = x.shape[1]
n_classes = Y.shape[1]
print(n_features)
print(n_classes)

4
3


In [ ]:
from keras.models import Sequential
from keras.layers import Dense

def create_custom_model(input_dim, output_dim, nodes, n=1, name='model'):
    def create_model():
        # Create model
        model = Sequential(name=name)
        for i in range(n):
            model.add(Dense(nodes, input_dim=input_dim, activation='relu'))
        model.add(Dense(output_dim, activation='softmax'))

        # Compile model
        model.compile(loss='categorical_crossentropy', 
                      optimizer='adam', 
                      metrics=['accuracy'])
        return model
    return create_model

models = [create_custom_model(n_features, n_classes, 8, i, 'model_{}'.format(i)) 
          for i in range(1, 4)]

for create_model in models:
    create_model().summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_112 (Dense)            (None, 8)                 40        
_________________________________________________________________
dense_113 (Dense)            (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_114 (Dense)            (None, 8)                 40        
_________________________________________________________________
dense_115 (Dense)            (None, 8)                 72        
_________________________________________________________________
dense_116 (Dense)            (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-tr

In [ ]:
from keras.callbacks import TensorBoard

history_dict = {}

# TensorBoard Callback
cb = TensorBoard()

for create_model in models:
    model = create_model()
    print('Model name:', model.name)
    history_callback = model.fit(X_train, Y_train,
                                 batch_size=5,
                                 epochs=50,
                                 verbose=0,
                                 validation_data=(X_test, Y_test),
                                 callbacks=[cb])
    score = model.evaluate(X_test, Y_test, verbose=0)
    s1=model.evaluate(X_train, Y_train)
    print('Test loss:', score[0])
    print('Test accuracy:', score[1])
    print('Train loss:', s1[0])
    print('Train Accuracy:',s1[1])
    
    history_dict[model.name] = [history_callback, model]

Model name: model_1
4/4 [==============================] - 0s 3ms/step - loss: 0.2165 - accuracy: 0.9333
Test loss: 0.21383020281791687
Test accuracy: 0.9333333373069763
Train loss: 0.21649904549121857
Train Accuracy: 0.9333333373069763
Model name: model_2
4/4 [==============================] - 0s 4ms/step - loss: 0.0837 - accuracy: 0.9750
Test loss: 0.15897171199321747
Test accuracy: 0.9333333373069763
Train loss: 0.08369337767362595
Train Accuracy: 0.9750000238418579
Model name: model_3
4/4 [==============================] - 0s 4ms/step - loss: 0.0725 - accuracy: 0.9667
Test loss: 0.12398666888475418
Test accuracy: 0.9333333373069763
Train loss: 0.07250497490167618
Train Accuracy: 0.9666666388511658
